apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rollout-demo
  name: rollout-demo-daniel-canary
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: rollout-demo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
